CREATE TABLE IF NOT EXISTS users (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  
  PRIMARY KEY (id),
  UNIQUE KEY (email)
);