CREATE TABLE IF NOT EXISTS products (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Text` TEXT NOT NULL,
  `UserId` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (id),
  FOREIGN KEY (UserId) REFERENCES users(ID)
);